Repository google/docsy, pull requests merged in 2021-12, with the labels that each got.

#790 Bump Bootstrap, Mermaid and KaTeX to their latest versions
  layouts/partials/scripts.html
  userguide/content/en/docs/Adding content/diagrams-and-formulae/index.md
Labels: cla: yes

#786 Support hiding single/root breadcrumbs
  layouts/partials/breadcrumb.html
Labels: cla: yes

#792 Fixing typo
  assets/scss/_colors.scss
Labels: cla: yes

#788 User guide: add section 'Deployment with Amazon S3 + Amazon Cloudfront'
  userguide/content/en/about/_index.md
  userguide/content/en/docs/Deployment/_index.md
  userguide/content/en/docs/_index.md
Labels: cla: yes

#789 Update de.toml
  i18n/de.toml
Labels: cla: yes

#813 Delete .github directory, reverting #779
  .github/settings.yml
Labels: admin

#814 Whitespace cleanup in navbar.html
  layouts/partials/navbar.html
Labels: cleanup/refactoring
