Repository google/docsy, pull requests merged in 2022-08, with the labels that each got.

#1098 Update Google Analytics section of UG
  userguide/config.toml
  userguide/content/en/docs/adding-content/feedback.md
Labels: user guide

#1164 Drop FontAwesome static/webfonts file copies, mount package
  assets/scss/_variables.scss
  config.toml
  static/webfonts/fa-brands-400.eot
  static/webfonts/fa-brands-400.svg
  static/webfonts/fa-brands-400.ttf
  static/webfonts/fa-brands-400.woff
  static/webfonts/fa-brands-400.woff2
  static/webfonts/fa-regular-400.eot
  static/webfonts/fa-regular-400.svg
  static/webfonts/fa-regular-400.ttf
  static/webfonts/fa-regular-400.woff
  static/webfonts/fa-regular-400.woff2
  static/webfonts/fa-solid-900.eot
  static/webfonts/fa-solid-900.svg
  static/webfonts/fa-solid-900.ttf
  static/webfonts/fa-solid-900.woff
  static/webfonts/fa-solid-900.woff2
Labels: cleanup/refactoring

#1149 Update Prism JS and CSS to v1.28.0
  static/css/prism.css
  static/js/prism.js
Labels: dependencies

#1172 Check links in the user guide
  package.json
  userguide/.gitignore
  userguide/.htmltest.yml
  userguide/Makefile
  userguide/package.json
Labels: infrastructure

#1173 Build before checking links
  userguide/package.json
Labels: infrastructure

#1179 Search font fix
  assets/scss/_search.scss
Labels: dependencies, design/style

#1181 NPM: pin dep versions and add update script
  package.json
Labels: infrastructure

#1183 scripts partial: whitespace and other cleanup
  layouts/partials/scripts.html
Labels: cleanup/refactoring

#1184 Config as YAML for Docsy and UG
  config.toml
  config.yaml
  userguide/config.toml
  userguide/config.yaml
Labels: cleanup/refactoring, infrastructure

#1189 navbar.html partial whitespace cleanup
  layouts/partials/navbar.html
Labels: cleanup/refactoring

#1191 Upgrade to Bootstrap 4.6.2 and FontAwesome 6.1.2
  CHANGELOG.md
  package.json
Labels: dependencies, bootstrap

#1193 Blog layout: streamline and fix styling RSS button
  assets/scss/_blog.scss
  layouts/blog/baseof.html
Labels: design/style

#1208 map keys must be unique in YAML
  userguide/content/en/docs/get-started/docsy-as-module/start-from-scratch.md
Labels: docsy-docs
