Repository google/docsy, pull requests merged in 2022-02, with the labels that each got.

#871 Enable to pull in docsy as hugo module
  config.toml
  dependencies/assets/bootstrap/README.txt
  dependencies/assets/bootstrap/scss/_vendor/README.txt
  dependencies/assets/bootstrap/scss/_vendor/_rfs.scss
  dependencies/config.toml
  dependencies/go.mod
  go.mod
  go.sum
  netlify.toml
  userguide/config.toml
Labels: module

#898 User guide config: use mounts rather than the old contentDir param
  userguide/config.toml
Labels: user guide

#902 Netlify: use docs-install before building the User Guide
  netlify.toml
  package.json
Labels: infrastructure

#904 Add support for Bootstrap and FontAwesome via NPM packages
  config.toml
  package.json
  userguide/package.json
Labels: infrastructure

#905 Fix: shortcode 'lead' produces invalid HTML (#527)
  layouts/shortcodes/blocks/lead.html
Labels: cleanup/refactoring
