Repository google/docsy, pull requests merged in 2023-05, with the labels that each got.

#1475 Drop mycplus.com iframe from Shortcode page
  userguide/content/en/docs/adding-content/shortcodes/index.md
Labels: user guide

#1376 Update to bootstrap 5: adapt shortcode 'cardpane'
  CHANGELOG.md
  assets/scss/shortcodes/cards-pane.scss
  layouts/shortcodes/card-code.html
  layouts/shortcodes/card.html
  layouts/shortcodes/cardpane.html
  userguide/content/en/docs/adding-content/shortcodes/index.md
Labels: bootstrap, shortcodes

#1502 [BSv5] fix horizontal scrollbar issues
  layouts/community/list.html
  layouts/shortcodes/blocks/cover.html
  layouts/shortcodes/blocks/lead.html
  layouts/shortcodes/blocks/section.html
Labels: bootstrap

#1501 [BSv5] fix main container height
  assets/scss/_main-container.scss
Labels: bootstrap

#1523 [BSv5] Footer: drop flex-shrink tweak + other adjustments
  CHANGELOG.md
  assets/scss/_variables.scss
  layouts/partials/footer.html
Labels: bootstrap

#1527 Minify hugo-served pages
  userguide/package.json
Labels: infrastructure

#1447 [BSv5] Refactor Click-to-copy
  CHANGELOG.md
  assets/js/click-to-copy.js
  assets/scss/_code.scss
  layouts/partials/scripts.html
  userguide/content/en/docs/adding-content/lookandfeel.md
Labels: bootstrap

#1456 Adjust Mermaid block styling and block content
  assets/scss/_code.scss
  layouts/_default/_markup/render-codeblock-mermaid.html
Labels: design/style, e0-minutes
