Repository google/docsy, pull requests merged in 2023-11, with the labels that each got.

#1671 Tabbed panes: fix styling when not at top-level & other tweaks
  assets/scss/shortcodes/tabbed-pane.scss
Labels: design/style

#1701 Upgrade Hugo to 0.120.3, and Node engine constraint
  package.json
Labels: dependencies, infrastructure

#1678 Algolia search, fix: point js + css file to specific version
  layouts/partials/head.html
  layouts/partials/scripts.html
Labels: search

#1710 Recover RSS round-button style
  assets/scss/_blog.scss
Labels: design/style, e0-minutes

#1711 Upgrade to Hugo 0.120.4, which include security patch
  package.json
Labels: dependencies

#1722 Update package.json: adjust dependencies
  package.json
Labels: infrastructure

#1217 Offer Docsy as a single Hugo Module
  assets/bootstrap/README.txt
  assets/bootstrap/scss/_vendor/README.txt
  assets/bootstrap/scss/_vendor/_rfs.scss
  dependencies/config.toml
  dependencies/go.mod
  dependencies/go.sum
  go.mod
  go.sum
  hugo.yaml
  netlify.toml
  package.json
Labels: cleanup/refactoring, infrastructure, module

#1732 Bump Dockerfile to latest version
  Dockerfile
Labels: docker

#1700 add post_view_this to i18n ja
  i18n/ja.toml
Labels: e0-minutes, i18n

#1736 Use SCSS `join()` rather than `prepend()`
  CHANGELOG.md
  assets/scss/_variables.scss
  assets/scss/main.scss
  assets/scss/support/_functions.scss
Labels: cleanup/refactoring

#1727 Enable page feedback even without a Google analytics ID
  CHANGELOG.md
  layouts/_default/content.html
  layouts/docs/list.html
  layouts/partials/feedback.html
  layouts/swagger/list.html
  package.json
  userguide/content/en/docs/adding-content/feedback.md
  userguide/hugo.yaml
Labels: docsy-docs, analytics

#1726 [GA4] Emit `page_helpful` events for page feedback
  CHANGELOG.md
  layouts/partials/feedback.html
  userguide/content/en/docs/adding-content/feedback.md
Labels: breaking change, analytics

#1755 [blog] Docsy priorities for 2024
  userguide/content/en/blog/2023/bootstrap-5-migration.md
  userguide/content/en/blog/2023/docsy-0.7.md
  userguide/content/en/blog/2023/priorities-for-2024.md
Labels: roadmap, governance, blog
