Repository google/docsy, pull requests merged in 2023-02, with the labels that each got.

#1272 Shortcode imgproc: add crop command
  layouts/shortcodes/imgproc.html
  userguide/content/en/docs/adding-content/shortcodes/index.md
Labels: user guide, shortcodes

#1402 Upgrade to Hugo 0.110.0 and normalize script names
  package.json
  userguide/package.json
Labels: dependencies, infrastructure

#1403 Upgrade FontAwesome to 6.3.0 and tweak update script
  package.json
Labels: dependencies, infrastructure

#1404 Rename config.yaml to hugo.yaml
  hugo.yaml
  userguide/hugo.yaml
Labels: infrastructure

#1382 [BSv5][JS]: fix dropdowns and more
  assets/js/base.js
  layouts/partials/footer.html
  layouts/partials/head.html
  layouts/partials/navbar-lang-selector.html
  layouts/partials/navbar-version-selector.html
  layouts/partials/sidebar-tree.html
  netlify.toml
Labels: bootstrap

#1407 [BSv5] Drop invalid and unnecessary tooltip attribute
  layouts/partials/footer.html
Labels: bootstrap, cleanup/refactoring

#1415 [BS5] Adjust HTML of dropdowns for version and lang
  layouts/partials/navbar-lang-selector.html
  layouts/partials/navbar-version-selector.html
Labels: bootstrap

#1409 Module setup: bump FontAwesome to latest version 6.3.0
  dependencies/go.mod
  dependencies/go.sum
  go.mod
  go.sum
  userguide/content/en/docs/Updating/Convert-site-to-module.md
Labels: module

#1429 [BSv5] Adjusted offline search popover
  assets/js/offline-search.js
Labels: bootstrap

#1434 Search resource cleanup and style tweak
  assets/js/offline-search.js
  assets/js/search.js
  assets/scss/_search.scss
Labels: design/style, cleanup/refactoring

#1428 package.json: add license and homepage
  package.json
Labels: e0-minutes, p3-low
