Repository google/docsy, pull requests merged in 2023-03, with the labels that each got.

#1439 Pin Docsy version in other installation options
  userguide/content/en/docs/get-started/other-options.md
Labels: docsy-docs

#1451 Use <pre> tag for mermaid code blocks
  layouts/_default/_markup/render-codeblock-mermaid.html
Labels: e0-minutes

#1454 Reformat SCSS sources using Prettier
  assets/scss/_alerts.scss
  assets/scss/_blog.scss
  assets/scss/_boxes.scss
  assets/scss/_breadcrumb.scss
  assets/scss/_buttons.scss
  assets/scss/_code.scss
  assets/scss/_colors.scss
  assets/scss/_content.scss
  assets/scss/_drawio.scss
  assets/scss/_main-container.scss
  assets/scss/_pageinfo.scss
  assets/scss/_search.scss
  assets/scss/_sidebar-toc.scss
  assets/scss/_sidebar-tree.scss
  assets/scss/_taxonomy.scss
  assets/scss/_variables.scss
  assets/scss/blocks/_blocks.scss
  assets/scss/blocks/_cover.scss
  assets/scss/rtl/_main.scss
  assets/scss/rtl/_spacing.scss
  assets/scss/section-index.scss
  assets/scss/shortcodes.scss
  assets/scss/shortcodes/cards-pane.scss
  assets/scss/support/_mixins.scss
  assets/scss/support/_utilities.scss
Labels: cleanup/refactoring

#1455 [BSv5] Drop `bg-gradient-variant()` mixin
  CHANGELOG.md
  assets/scss/_boxes.scss
  assets/scss/support/_mixins.scss
  layouts/community/list.html
  layouts/partials/community_links.html
  layouts/shortcodes/blocks/lead.html
  layouts/shortcodes/blocks/section.html
  userguide/content/en/docs/adding-content/lookandfeel.md
Labels: bootstrap

#1458 Delete duplicate mixin definitions
  assets/scss/support/_mixins.scss
  assets/scss/support/_utilities.scss
Labels: cleanup/refactoring

#1462 [BSv5] Docsy variables cleanup and BS version test
  assets/scss/_variables.scss
  assets/scss/_variables_forward.scss
  assets/scss/main.scss
Labels: bootstrap, cleanup/refactoring

#1467 [BSv5] blocks/cover row/col fix
  assets/scss/blocks/_cover.scss
  layouts/shortcodes/blocks/cover.html
  userguide/content/en/_index.html
  userguide/content/en/docs/adding-content/iconsimages.md
Labels: bootstrap

#1398 shortcode 'blocks/lead':lead: improvements
  layouts/shortcodes/blocks/lead.html
  userguide/content/en/_index.md
  userguide/content/en/docs/adding-content/shortcodes/index.md
Labels: shortcodes

#1472 [BSv5] blocks/section row-col hierarchy fix
  CHANGELOG.md
  assets/scss/_boxes.scss
  layouts/_default/content.html
  layouts/_default/list.html
  layouts/_default/search.html
  layouts/_default/single.html
  layouts/community/list.html
  layouts/shortcodes/blocks/lead.html
  layouts/shortcodes/blocks/section.html
  userguide/content/en/_index.md
  userguide/content/en/about/index.md
  userguide/content/en/docs/adding-content/shortcodes/index.md
  userguide/hugo.yaml
Labels: bootstrap, breaking change
