Repository google/docsy, pull requests merged in 2023-01, with the labels that each got.

#517 Update to Bootstrap v5: initial work
  assets/scss/_boxes.scss
  assets/scss/_colors.scss
  dependencies/go.mod
  go.mod
  go.sum
  layouts/_default/search.html
  layouts/blog/list.html
  layouts/partials/featured-image.html
  layouts/partials/footer.html
  layouts/partials/navbar.html
  layouts/partials/page-meta-links.html
  layouts/partials/pager.html
  layouts/partials/sidebar-tree.html
  package.json
Labels: bootstrap

#1361 [BSv5] More utility updates
  layouts/blog/baseof.html
  layouts/blog/baseof.print.html
  layouts/blog/list.html
  layouts/docs/baseof.html
  layouts/docs/baseof.print.html
  layouts/partials/pager.html
  layouts/partials/sidebar-tree.html
  layouts/shortcodes/tabpane.html
  layouts/swagger/baseof.html
  userguide/config.yaml
  userguide/content/en/_index.html
  userguide/content/en/docs/adding-content/shortcodes/index.md
Labels: bootstrap

#1363 [BSv5] YIQ color - final changes
  assets/scss/_colors.scss
  assets/scss/_variables.scss
Labels: bootstrap

#1367 [BSv5] Adjust media-breakpoint-down() argument
  assets/scss/_nav.scss
  assets/scss/_sidebar-tree.scss
  assets/scss/main.scss
Labels: bootstrap

#1366 Shortcode 'tabpane': minor fix
  layouts/shortcodes/tabpane.html
Labels: shortcodes

#1371 Tab panes: adaptation to Bootstrap 5
  layouts/shortcodes/tabpane.html
Labels: bootstrap, shortcodes

#1374 [BSv5]: make docsy point to latest version of dependencies
  go.mod
  go.sum
Labels: bootstrap, module

#1373 [BSv5] Footer fixes
  layouts/partials/footer.html
Labels: bootstrap

#1378 [BSv5] Script for persisting tabpanes: Fix
  static/js/tabpane-persist.js
Labels: bootstrap, shortcodes

#1384 [BSv5] replace lighten by tint-color, and var/func clean up
  CHANGELOG.md
  assets/scss/_drawio.scss
  assets/scss/_search.scss
  assets/scss/_variables.scss
  assets/scss/support/_functions.scss
Labels: bootstrap
