Repository google/docsy, pull requests merged in 2024-05, with the labels that each got.

#1976 [CI] Add scripts to generate and check Chroma styles
  netlify.toml
  package.json
  tools/gen-chroma-styles.sh
Labels: CI/infra

#1977 [CI] Setup fix:format for the UG
  package.json
  userguide/content/en/docs/adding-content/lookandfeel.md
  userguide/package.json
Labels: cleanup/refactoring, docsy-docs, CI/infra

#1978 [UG] Document light/dark mode config
  userguide/content/en/docs/adding-content/lookandfeel.md
Labels: user guide

#1980 Contribution guidelines: document use of Prettier
  userguide/content/en/docs/contribution-guidelines/_index.md
Labels: CI/infra

#1982 [CI] use userguide/.prettierignore to specify files to ignore
  userguide/.prettierignore
  userguide/content/en/docs/_index.md
  userguide/package.json
Labels: CI/infra

#1984 Fix warning about LaTeX-incompatible input
  userguide/content/en/docs/adding-content/diagrams-and-formulae/index.md
Labels: user guide

#1986 Set package version to 0.10.1-dev
  CHANGELOG.md
  package.json
  userguide/hugo.yaml
Labels: CI/infra

#1994 UG site config cleanup re lang params
  userguide/hugo.yaml
Labels: cleanup/refactoring

#2000 Update Hugo to 0.126.1, script name tweaks, and more
  package.json
Labels: CI/infra

#2007 [CI] UG NPM script tweaks
  userguide/package.json
Labels: CI/infra

#2006 Cleanup of Google analytics templates
  layouts/_internal/google_analytics.html
  layouts/_internal/google_analytics_gtag.html
  layouts/partials/head.html
  userguide/content/en/docs/adding-content/feedback.md
Labels: cleanup/refactoring

#2020 [RTL] Drop unused style files
  assets/scss/rtl/_main.scss
  assets/scss/rtl/_spacing.scss
Labels: i18n

#1435 User guide, deployment page: add section 'Deployment on GitHub Pages'
  userguide/content/en/docs/deployment/_index.md
Labels: user guide
