Repository google/docsy, pull requests merged in 2024-10, with the labels that each got.

#2086 Replaced some instances of older config.yaml and config.json in userguide
  userguide/content/en/docs/updating/convert-site-to-module.md
Labels: user guide

#2058 Update ar.toml -Enhance Arabic User Experience with Feedback Labels and Correct Diacritics
  i18n/ar.toml
Labels: i18n

#2092 Update Hugo to 0.133.1, and other pkgs
  package.json
Labels: CI/infra

#2093 RTL support via a single main style file
  .vscode/cspell.json
  assets/scss/support/_rtl.scss
  layouts/partials/head-css.html
  userguide/content/en/docs/language/_index.md
  userguide/package.json
Labels: i18n

#2095 [RTL] UG: set `en` to `rtl` for testing purposes
  userguide/hugo.yaml
Labels: i18n

#2096 [RTL] Drop unused BS asset and scripts to fetch it
  assets/_vendor/bootstrap/dist/css/bootstrap.rtl.css
  hugo.yaml
  package.json
Labels: i18n

#2099 [fa] i18n: add remaining entries
  i18n/fa.toml
Labels: i18n

#2106 Update packages: Hugo to 0.136.5
  package.json
Labels: dependencies, CI/infra
