Repository google/docsy, pull requests merged in 2024-01, with the labels that each got.

#1783 Cleanup: drop NPM script that is no longer needed, tweak job names
  .github/workflows/smoke.yaml
  .github/workflows/test.yaml
  package.json
Labels: cleanup/refactoring

#1633 Fix warning: '.File.UniqueID on zero object' (#1007)
  layouts/partials/section-index.html
Labels: cleanup/refactoring, e0-minutes, fix

#1790 [CI] Fix markdown-link-check ignore pattern & NPM link vers update
  .markdown-link-check.json
  CHANGELOG.md
  userguide/content/en/docs/get-started/docsy-as-module/installation-prerequisites.md
  userguide/content/en/docs/get-started/other-options.md
Labels: cleanup/refactoring, infrastructure

#1795 [CI] Smoke test new site from Hugo-module Docsy as well
  .github/workflows/smoke.yaml
  tools/make-site.sh
Labels: infrastructure
