Repository google/docsy, pull requests merged in 2024-04, with the labels that each got.

#1913 [Dark-mode] Tweak of param, file and resource names
  assets/js/dark-mode.js
  assets/scss/_nav.scss
  layouts/partials/navbar.html
  layouts/partials/scripts.html
  userguide/hugo.yaml
Labels: enhancement

#1915 Adjust pageinfo bg to be compatible with dark-mode
  assets/scss/_pageinfo.scss
  userguide/content/en/docs/adding-content/shortcodes/index.md
Labels: breaking change

#1923 Drop deprecated shortcode 'card-code'
  CHANGELOG.md
  layouts/shortcodes/card-code.html
Labels: shortcodes

#1939 Upgrade Hugo to 0.125.2
  package.json
Labels: dependencies

#1914 [UG] Explain how to enable the light/dark-mode menu
  userguide/content/en/docs/adding-content/lookandfeel.md
Labels: user guide

#1948 Drop RSS layout in favor of Hugo's default
  layouts/_default/list.rss.xml
Labels: cleanup/refactoring

#1950 Upgrade to Hugo 0.125.4
  package.json
  tools/install-hugo.sh
Labels: dependencies, CI/infra

#1955 Bump Persian fonts to latest version
  assets/scss/rtl/_main.scss
Labels: i18n

#1958 [UG] Syntax highlighting styles for both light and dark modes
  assets/scss/_chroma-onedark.css
  assets/scss/_chroma-tango.css
  userguide/assets/scss/_styles_project.scss
  userguide/hugo.yaml
Labels: user guide, design/style

#1963 Format mermaid.html
  layouts/partials/scripts/mermaid.html
Labels: cleanup/refactoring

#1969 Format lookandfeel.md - no content changes
  userguide/content/en/docs/adding-content/lookandfeel.md
Labels: cleanup/refactoring
