Repository google/docsy, pull requests merged in 2024-03, with the labels that each got.

#1877 Upgrade to Hugo 0.123.x
  package.json
Labels: dependencies, CI/infra

#1885 Mermaid diagram with diagram specific settings: fix 'uncaught TypeError'
  layouts/partials/scripts/mermaid.html
  userguide/content/en/docs/adding-content/diagrams-and-formulae/index.md
Labels: e1-hours, fix

#1886 Bump jquery to latest released version 3.7.1
  layouts/partials/head.html
Labels: e0-minutes

#1563 Upgrade to Bootstrap 5.3.3
  assets/_vendor/bootstrap/scss/_rfs.scss
  go.mod
  go.sum
  package.json
  userguide/package.json
Labels: dependencies, e0-minutes, module

#1891 Update Hugo to 0.123.8, and prettier
  package.json
Labels: CI/infra

#1892 [BS5.3] Replace text-muted by text-body-secondary
  assets/js/offline-search.js
  assets/scss/_pageinfo.scss
  layouts/blog/content.html
  layouts/blog/list.html
  layouts/partials/featured-image.html
  layouts/partials/print/content-blog.html
  layouts/shortcodes/card.html
  layouts/shortcodes/imgproc.html
Labels: bootstrap

#1905 Update Hugo to 0.124.1
  package.json
Labels: dependencies, CI/infra

#1898 Delete UG `layouts/sitemap.xml`
  userguide/layouts/sitemap.xml
Labels: user guide

#1896 [BS5.3] Replace `.navbar-dark` by data attribute and other style adjustments
  assets/scss/_search.scss
  assets/scss/_variables.scss
  layouts/partials/navbar.html
Labels: bootstrap

#1909 Color-mode / dark-mode support
  assets/js/color-mode.js
  assets/scss/_nav.scss
  layouts/partials/navbar.html
  layouts/partials/scripts.html
  layouts/partials/theme-toggler.html
  userguide/hugo.yaml
Labels: enhancement, UX, design/style
