Repository google/docsy, pull requests merged in 2024-08, with the labels that each got.

#2061 [UG][cleanup] Updating Docsy: run Prettier and cleanup front matter
  userguide/content/en/docs/updating/_index.md
Labels: cleanup/refactoring

#2063 [infra] Upgrade all NPM packages, including Hugo to 0.131.0
  package.json
  userguide/package.json
Labels: CI/infra

#2064 [CI] Don't check links under Windows
  .github/workflows/test.yaml
Labels: CI/infra

#2066 [CI][UG] Serve to memory and disable fast render
  userguide/package.json
Labels: user guide, CI/infra

#2067 [feat] Support `contributingUrl` param
  CHANGELOG.md
  layouts/partials/community_links.html
  userguide/content/en/docs/adding-content/content.md
Labels: enhancement

#1541 Documents the body_class parameter
  userguide/content/en/docs/adding-content/lookandfeel.md
Labels: user guide
