Repository google/docsy, pull requests merged in 2024-02, with the labels that each got.

#1744 Fix links for single language sites
  layouts/partials/page-meta-links.html
Labels: p0-critical

#1808 Whitespace cleanup in page-meta-links.html
  layouts/partials/page-meta-links.html
Labels: cleanup/refactoring

#1810 Use cpy-cli for OS-independent file copy
  package.json
Labels: CI/infra

#1811 [CI] test:all should also check/fix format
  package.json
Labels: CI/infra

#1463 Drop AnchorJS in favor of Hugo markdown render hook
  assets/js/anchor.js
  layouts/_default/_markup/render-heading.html
  layouts/partials/scripts.html
Labels: e0-minutes, CI/infra

#1500 layouts: split footer partial in several partials
  layouts/partials/footer.html
  layouts/partials/footer/center.html
  layouts/partials/footer/left.html
  layouts/partials/footer/links.html
  layouts/partials/footer/right.html
Labels: p1-high

#1825 Add link to example site (themes.gohugo.io)
  theme.toml
Labels: example site, e0-minutes

#1830 user guide, multi-language settings: improve config options
  userguide/content/en/docs/get-started/basic-configuration.md
  userguide/content/en/docs/language/_index.md
Labels: user guide, e0-minutes, i18n

#1828 user guide, definition listings of site params: add 'params' context
  userguide/content/en/docs/adding-content/content.md
  userguide/content/en/docs/adding-content/iconsimages.md
  userguide/content/en/docs/adding-content/lookandfeel.md
  userguide/content/en/docs/adding-content/repository-links.md
  userguide/content/en/docs/adding-content/search.md
  userguide/content/en/docs/adding-content/versioning.md
  userguide/content/en/docs/get-started/basic-configuration.md
Labels: enhancement, user guide

#1834 Issue template 'enhancement': Fix error
  .github/ISSUE_TEMPLATE/enhancement.md
Labels: e0-minutes, CI/infra, fix

#1821 Support date range in footer copyright element
  CHANGELOG.md
  assets/scss/main.scss
  layouts/partials/footer/copyright.html
  userguide/assets/scss/_styles_project.scss
  userguide/hugo.yaml
Labels: enhancement

#1844 [UG] Refer to Bootstrap 5 doc pages and files
  userguide/content/en/docs/adding-content/lookandfeel.md
Labels: user guide

#1843 [UG] Document how to style and hide last-modified page notes
  userguide/content/en/docs/adding-content/repository-links.md
Labels: user guide

#1865 0.9.0 release report updates
  userguide/content/en/blog/2024/0.9.0.md
Labels: blog
