Repository google/docsy, pull requests merged in 2024-11, with the labels that each got.

#2112 Update pkgs, with Hugo to 0.137.0
  package.json
Labels: dependencies

#2118 [CI] Make build checks pass again, skip .md link checking
  package.json
Labels: CI/infra

#2104 User guide: correct instructions on how to disable RSS feed
  userguide/content/en/docs/adding-content/content.md
Labels: user guide

#2120 External link checking + project pages
  .markdown-link-check.json
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  layouts/partials/page-meta-lastmod.html
  package.json
  userguide/.htmltest.yml
  userguide/.prettierignore
  userguide/Makefile
  userguide/content/en/project/_index.md
  userguide/hugo.yaml
  userguide/package.json
  userguide/static/refcache.json
Labels: enhancement, CI/infra

#2124 [CI] Restore format check as a part of `npm test`
  package.json
Labels: CI/infra

#2125 Upgrade Hugo and merge optional deps into dev
  package.json
Labels: dependencies, CI/infra

#2128 [CI] Handle creation of empty Hugo-modules for deps
  package.json
  tools/mkdirp-hugo-mod.js
  userguide/content/en/docs/get-started/other-options.md
Labels: CI/infra

#2129 Upgrade Hugo and FontAwesome
  go.mod
  go.sum
  package.json
Labels: dependencies, CI/infra
