Repository google/docsy, pull requests merged in 2025-02, with the labels that each got.

#1858 User guide, LaTeX: typesetting of formulae using standard syntax
  layouts/partials/scripts.html
  layouts/partials/scripts/katex.html
  layouts/partials/scripts/mhchem.html
  userguide/content/en/docs/adding-content/diagrams-and-formulae/index.md
  userguide/hugo.yaml
Labels: user guide

#2191 Upgrade Hugo to 0.143.1, etc
  package.json
Labels: dependencies, CI/infra

#2192 [feat] Add base support of td-content-after-header hook
  CHANGELOG.md
  layouts/_default/content.html
  layouts/_default/td-content-after-header.html
  layouts/blog/content.html
  layouts/docs/list.html
  userguide/static/refcache.json
Labels: enhancement
